project_id = "mmyaeapowwfwaumjpdua"

[functions.subscription]
verify_jwt = false

[functions.ai-coach]
verify_jwt = false

[functions.track-referral]
verify_jwt = false

[functions.voice-transcribe]
verify_jwt = false
